export { HomePage } from "./Home/HomePage";
export { ProductList } from "./Product/ProductList";
// export { SearchPage } from "./SearchPage";
export { ProductDetail } from "./ProductDetail";
export { Login } from "./Login";
export { Registration } from "./Registration";
export { DashboardPage } from"./Dashboard/DashboardPage";
export { CartPage } from "./Cart/CartPage";
export { OrderPage } from "./Order/OrderPage";
export { PageNotFound } from "./PageNotFound";